//! VanSwarm MCP server — tool handlers.
//!
//! Exposes the VanSwarm agent framework as MCP tools so any MCP-capable
//! client (Cursor, Claude Desktop, etc.) can:
//!
//! * Run a full ReAct reasoning loop via `vanswarm_run_agent`.
//! * Store and search episodic memory via `vanswarm_memory_*` tools.
//! * Inspect framework status via `vanswarm_framework_info`.
//! * Browse VanSwarm documentation via `resources/list` and `resources/read`.
//! * Scaffold agents, workflows, and tools via `prompts/list` and `prompts/get`.
//!
//! The server auto-detects the LLM provider at startup by checking:
//!   `ANTHROPIC_API_KEY` → AnthropicProvider (default model: claude-opus-4-6)
//!   `OPENAI_API_KEY`    → OpenAiProvider    (default model: gpt-4o)
//!   `GEMINI_API_KEY`    → GeminiProvider    (default model: gemini-2.0-flash)
//!
//! Override the model with `RUSTMASTRA_MODEL`.
//! Set `VANSWARM_DOCS_ROOT` to the documentation directory to enable resources.

use std::{path::PathBuf, sync::Arc};

use rmcp::{
    RoleServer,
    handler::server::{router::tool::ToolRouter, wrapper::Parameters},
    model::{
        AnnotateAble, CallToolResult, Content, ErrorData as McpError, GetPromptRequestParams,
        GetPromptResult, Implementation, ListPromptsResult, ListResourcesResult,
        PaginatedRequestParams, Prompt, PromptArgument, PromptMessage, PromptMessageRole,
        ProtocolVersion, RawResource, ReadResourceRequestParams, ReadResourceResult,
        ResourceContents, ServerCapabilities, ServerInfo,
    },
    service::RequestContext,
    tool, tool_handler, tool_router, ServerHandler,
};
use schemars::JsonSchema;
use serde::Deserialize;

use vanswarm_core::{
    config::{AgentConfig, ModelConfig},
    providers::ModelProvider,
    react::{run_agent_with_metrics, ReActAgent},
    LocalToolRegistry, TimeTool,
};
use vanswarm_memory::{Memory, MemoryEntry};

// ─────────────────────────────────────────────────────────────────────────────
// Parameter structs (schemars 1.0 JsonSchema required by rmcp #[tool] macro)
// ─────────────────────────────────────────────────────────────────────────────

/// Parameters for `vanswarm_run_agent`.
#[derive(Debug, Deserialize, JsonSchema)]
pub struct RunAgentParams {
    /// The user prompt or task description for the agent to solve.
    pub prompt: String,

    /// Optional system prompt to set the agent's persona or constraints.
    /// Example: "You are a concise Rust expert. Use tools where appropriate."
    #[serde(default)]
    pub system_prompt: Option<String>,

    /// LLM model override. Defaults to the server-detected default.
    /// Examples: "claude-opus-4-6", "gpt-4o", "gemini-2.0-flash"
    #[serde(default)]
    pub model: Option<String>,

    /// Maximum number of ReAct iterations before the agent gives up.
    /// Default: 10. Lower for faster responses; raise for complex multi-step tasks.
    #[serde(default)]
    pub max_iterations: Option<u32>,
}

/// Parameters for `vanswarm_memory_store`.
#[derive(Debug, Deserialize, JsonSchema)]
pub struct MemoryStoreParams {
    /// The fact, observation, or event to remember.
    pub content: String,
}

/// Parameters for `vanswarm_memory_search`.
#[derive(Debug, Deserialize, JsonSchema)]
pub struct MemorySearchParams {
    /// Full-text search query (case-insensitive substring match).
    pub query: String,

    /// Maximum number of results to return. Default: 10.
    #[serde(default)]
    pub limit: Option<u32>,
}

/// Parameters for `vanswarm_memory_recent`.
#[derive(Debug, Deserialize, JsonSchema)]
pub struct MemoryRecentParams {
    /// Maximum number of entries to return, newest first. Default: 10.
    #[serde(default)]
    pub limit: Option<u32>,
}

/// Empty parameter struct for `vanswarm_framework_info`.
#[derive(Debug, Deserialize, JsonSchema)]
pub struct NoParams {}

// ─────────────────────────────────────────────────────────────────────────────
// FrameworkTools — shared state + tool router
// ─────────────────────────────────────────────────────────────────────────────

/// Composite MCP server exposing VanSwarm agent framework capabilities.
///
/// All fields are `Clone` + `Send + Sync` so the struct can be shared across
/// concurrent MCP requests via `Arc`-wrapped state.
#[derive(Clone)]
pub struct FrameworkTools {
    /// Auto-detected LLM provider. `None` if no API key was found at startup.
    provider: Option<Arc<dyn ModelProvider>>,
    /// Default model for the detected provider (e.g. "claude-opus-4-6").
    default_model: String,
    /// Name of the active provider for display in `framework_info`.
    provider_name: String,
    /// Episodic memory — in-memory (FIFO) or libsql-backed when VANSWARM_DB_PATH set.
    memory: Arc<dyn Memory>,
    /// Root directory for documentation resources. `None` if not configured or not found.
    docs_root: Option<PathBuf>,
    /// Routing table generated by `#[tool_router]`.
    tool_router: ToolRouter<Self>,
}

#[tool_router]
impl FrameworkTools {
    /// Create with the given memory backend (in-memory or libsql).
    pub fn new(
        provider: Option<Arc<dyn ModelProvider>>,
        default_model: impl Into<String>,
        provider_name: impl Into<String>,
        memory: Arc<dyn Memory>,
        docs_root: Option<PathBuf>,
    ) -> Self {
        Self {
            provider,
            default_model: default_model.into(),
            provider_name: provider_name.into(),
            memory,
            docs_root,
            tool_router: Self::tool_router(),
        }
    }

    // ──────────────────────────────────────────────────────────────────────
    // Agent tool
    // ──────────────────────────────────────────────────────────────────────

    /// Run a VanSwarm ReAct agent on the given prompt.
    ///
    /// The agent reasons step-by-step (Thought → Action → Observation) and may
    /// call built-in tools (`time`) until it produces a final answer or hits
    /// `max_iterations`. Returns the final answer followed by run metrics.
    #[tool(description = "Run a VanSwarm ReAct agent. The agent reasons step-by-step, calling tools as needed, until it produces a final answer. Built-in tool: `time` (current UTC time). Ideal for multi-step reasoning, research, planning, and Q&A. Returns the final answer with run metrics (iterations, tool_calls).")]
    pub async fn vanswarm_run_agent(
        &self,
        Parameters(params): Parameters<RunAgentParams>,
    ) -> Result<CallToolResult, McpError> {
        let provider = match &self.provider {
            Some(p) => Arc::clone(p),
            None => {
                return Err(McpError::invalid_params(
                    "No LLM provider configured. Set ANTHROPIC_API_KEY, OPENAI_API_KEY, \
                     or GEMINI_API_KEY before calling run_agent.",
                    None,
                ))
            }
        };

        let model = params.model.as_deref().unwrap_or(&self.default_model).to_string();
        let max_iter = params.max_iterations.unwrap_or(10) as usize;

        let mut config =
            AgentConfig::new("mcp-agent", ModelConfig::new(model)).with_max_iterations(max_iter);

        if let Some(sys) = params.system_prompt {
            config = config.with_system_prompt(sys);
        }

        // Include built-in tools available to the agent during the ReAct loop.
        let registry = Arc::new(LocalToolRegistry::new().register(TimeTool));

        let agent = ReActAgent::new(config, provider, registry);

        match run_agent_with_metrics(&agent, params.prompt).await {
            Ok((answer, metrics)) => {
                let response = format!(
                    "{answer}\n\n---\n_iterations: {}, tool_calls: {}_",
                    metrics.iterations, metrics.tool_call_count
                );
                Ok(CallToolResult::success(vec![Content::text(response)]))
            }
            Err(e) => Err(McpError {
                code: rmcp::model::ErrorCode::INTERNAL_ERROR,
                message: e.to_string().into(),
                data: None,
            }),
        }
    }

    // ──────────────────────────────────────────────────────────────────────
    // Memory tools
    // ──────────────────────────────────────────────────────────────────────

    /// Store a fact or observation in the agent's episodic memory.
    ///
    /// Memory persists for the lifetime of the server process (FIFO, 1 000-entry
    /// cap). Use to share context between multiple `run_agent` calls.
    /// Returns the UUID of the stored entry.
    #[tool(description = "Store a fact, observation, or event in the agent's episodic memory. Memory persists for the server's lifetime (FIFO, 1 000-entry cap). Use to share context across run_agent calls. Returns the stored entry's UUID.")]
    pub async fn vanswarm_memory_store(
        &self,
        Parameters(params): Parameters<MemoryStoreParams>,
    ) -> Result<CallToolResult, McpError> {
        let entry = MemoryEntry::new(params.content);
        let id = entry.id;
        self.memory.store(entry).await.map_err(|e| McpError {
            code: rmcp::model::ErrorCode::INTERNAL_ERROR,
            message: e.to_string().into(),
            data: None,
        })?;
        Ok(CallToolResult::success(vec![Content::text(format!("stored id={id}"))]))
    }

    /// Full-text search in the agent's episodic memory.
    ///
    /// Performs a case-insensitive substring match against all stored entries.
    /// Returns matching entries formatted as `[id] timestamp — content`.
    #[tool(description = "Full-text search in episodic memory. Case-insensitive substring match. Returns matching entries as `[id] timestamp — content` lines, newest first.")]
    pub async fn vanswarm_memory_search(
        &self,
        Parameters(params): Parameters<MemorySearchParams>,
    ) -> Result<CallToolResult, McpError> {
        let limit = params.limit.unwrap_or(10) as usize;
        let entries = self.memory.search(&params.query, limit).await.map_err(|e| McpError {
            code: rmcp::model::ErrorCode::INTERNAL_ERROR,
            message: e.to_string().into(),
            data: None,
        })?;

        if entries.is_empty() {
            return Ok(CallToolResult::success(vec![Content::text(
                "No matching entries found.",
            )]));
        }

        let lines: Vec<String> = entries
            .iter()
            .map(|e| {
                format!(
                    "[{}] {} — {}",
                    e.id,
                    e.created_at.format("%Y-%m-%dT%H:%M:%SZ"),
                    e.content
                )
            })
            .collect();
        Ok(CallToolResult::success(vec![Content::text(lines.join("\n"))]))
    }

    /// Return the most recent entries in the agent's episodic memory.
    ///
    /// Entries are returned newest first, formatted as `[id] timestamp — content`.
    #[tool(description = "Return the most recent entries in episodic memory, newest first. Formatted as `[id] timestamp — content` lines.")]
    pub async fn vanswarm_memory_recent(
        &self,
        Parameters(params): Parameters<MemoryRecentParams>,
    ) -> Result<CallToolResult, McpError> {
        let limit = params.limit.unwrap_or(10) as usize;
        let entries = self.memory.recent(limit).await.map_err(|e| McpError {
            code: rmcp::model::ErrorCode::INTERNAL_ERROR,
            message: e.to_string().into(),
            data: None,
        })?;

        if entries.is_empty() {
            return Ok(CallToolResult::success(vec![Content::text("Memory is empty.")]));
        }

        let lines: Vec<String> = entries
            .iter()
            .map(|e| {
                format!(
                    "[{}] {} — {}",
                    e.id,
                    e.created_at.format("%Y-%m-%dT%H:%M:%SZ"),
                    e.content
                )
            })
            .collect();
        Ok(CallToolResult::success(vec![Content::text(lines.join("\n"))]))
    }

    // ──────────────────────────────────────────────────────────────────────
    // Info
    // ──────────────────────────────────────────────────────────────────────

    /// Return VanSwarm framework version, provider status, and capabilities.
    #[tool(description = "Return framework version, configured LLM provider, default model, and available capabilities. Use to check server health and configuration.")]
    pub async fn vanswarm_framework_info(
        &self,
        _params: Parameters<NoParams>,
    ) -> Result<CallToolResult, McpError> {
        let provider_status = if self.provider.is_some() {
            format!(
                "connected (provider: {}, default model: {})",
                self.provider_name, self.default_model
            )
        } else {
            "NOT configured — set ANTHROPIC_API_KEY, OPENAI_API_KEY, or GEMINI_API_KEY".to_string()
        };

        let docs_status = match &self.docs_root {
            Some(root) => format!("available (root: {})", root.display()),
            None => "not configured (set VANSWARM_DOCS_ROOT)".to_string(),
        };

        let info = format!(
            "VanSwarm Agent Framework\n\
             Version:        {version}\n\
             LLM provider:   {provider_status}\n\
             Built-in tools: time (UTC clock)\n\
             Memory:         episodic in-process (FIFO, 1 000 entries)\n\
             Docs:           {docs_status}\n\
             Agent pattern:  ReAct (Thought → Action → Observation)\n\
             Other patterns: EvaluatorOptimizer, PlanAndExecute, Supervisor\n\
             Providers:      Anthropic, OpenAI, Gemini\n\
             Telemetry:      run traces, token usage, cost estimation",
            version = env!("CARGO_PKG_VERSION"),
            provider_status = provider_status,
            docs_status = docs_status,
        );
        Ok(CallToolResult::success(vec![Content::text(info)]))
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Documentation resource helpers
// ─────────────────────────────────────────────────────────────────────────────

const DOCS_URI_PREFIX: &str = "vanswarm://docs/";

/// Walk `root` recursively and return all `.md` files as MCP `Resource` values.
///
/// Resources are sorted by URI for deterministic listing order.
fn collect_doc_resources(root: &std::path::Path) -> Vec<rmcp::model::Resource> {
    let mut resources = Vec::new();
    collect_recursive(root, root, &mut resources);
    resources.sort_by(|a, b| a.uri.cmp(&b.uri));
    resources
}

fn collect_recursive(
    root: &std::path::Path,
    dir: &std::path::Path,
    acc: &mut Vec<rmcp::model::Resource>,
) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_recursive(root, &path, acc);
        } else if path.extension().map_or(false, |e| e == "md") {
            let relative = path.strip_prefix(root).unwrap_or(&path);
            // Use forward slashes in URIs even on Windows.
            let rel_str = relative
                .components()
                .map(|c| c.as_os_str().to_string_lossy().into_owned())
                .collect::<Vec<_>>()
                .join("/");
            let uri = format!("{DOCS_URI_PREFIX}{rel_str}");
            let description = path
                .file_stem()
                .map(|s| s.to_string_lossy().replace(['-', '_'], " "));
            let raw = RawResource {
                uri: uri.clone(),
                name: rel_str,
                title: None,
                description,
                mime_type: Some("text/markdown".to_string()),
                size: path.metadata().ok().map(|m| m.len() as u32),
                icons: None,
                meta: None,
            };
            acc.push(raw.no_annotation());
        }
    }
}

/// Resolve a `vanswarm://docs/<path>` URI to a safe filesystem path under `docs_root`.
///
/// Returns `None` if:
/// - The URI does not start with `vanswarm://docs/`.
/// - The path contains `..`, a leading `/`, or a null byte.
/// - The canonicalized path is outside `docs_root`.
fn resolve_doc_uri(docs_root: &std::path::Path, uri: &str) -> Option<std::path::PathBuf> {
    let relative = uri.strip_prefix(DOCS_URI_PREFIX)?;

    // Reject obvious traversal attempts before touching the filesystem.
    if relative.contains("..") || relative.starts_with('/') || relative.contains('\0') {
        return None;
    }

    // Convert URI-style forward slashes to platform path separators.
    let rel_path: std::path::PathBuf = relative.split('/').collect();
    let full_path = docs_root.join(&rel_path);

    // Canonicalize both paths so symlinks cannot escape the root.
    let canonical_root = std::fs::canonicalize(docs_root).ok()?;
    let canonical_path = std::fs::canonicalize(&full_path).ok()?;

    if canonical_path.starts_with(&canonical_root) {
        Some(full_path)
    } else {
        None
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Scaffold prompt templates
// ─────────────────────────────────────────────────────────────────────────────

fn agent_scaffold_prompt(name: &str, model: &str) -> String {
    format!(
        r#"Create a new VanSwarm ReAct agent named `{name}` using model `{model}`.

## Steps

1. Add the following dependencies to your `Cargo.toml`:
```toml
vanswarm-core = {{ path = "crates/core" }}   # or version from crates.io
tokio = {{ version = "1", features = ["full"] }}
```

2. Create `src/main.rs` (or a module):
```rust
use std::sync::Arc;

use vanswarm_core::{{
    config::{{AgentConfig, ModelConfig}},
    providers::AnthropicProvider,   // or OpenAiProvider / GeminiProvider
    react::{{ReActAgent, run_agent}},
    LocalToolRegistry, TimeTool,
}};

#[tokio::main]
async fn main() -> anyhow::Result<()> {{
    // 1. Configure the provider (reads ANTHROPIC_API_KEY from env).
    let provider = AnthropicProvider::from_env()?;

    // 2. Build the agent config.
    let config = AgentConfig::new(
        "{name}",
        ModelConfig::new("{model}"),
    )
    .with_max_iterations(10)
    .with_system_prompt(
        "You are a helpful assistant. Use the available tools when appropriate.",
    );

    // 3. Set up the tool registry.
    let tools = Arc::new(LocalToolRegistry::new().register(TimeTool));

    // 4. Create the agent.
    let agent = ReActAgent::new(config, Arc::new(provider), tools);

    // 5. Run it.
    let answer = run_agent(&agent, "What time is it?").await?;
    println!("{{}}", answer);
    Ok(())
}}
```

## Next steps
- Add custom tools: implement the `Tool` trait and `.register(MyTool)` them.
- Enable chain-of-thought: `.enable_chain_of_thought(true)` on `AgentConfig`.
- Use `run_agent_with_metrics` to get iteration and tool-call counts.
- Use `run_agent_traced` for full APM traces with token usage and cost.
"#
    )
}

fn workflow_scaffold_prompt(name: &str) -> String {
    format!(
        r#"Create a new VanSwarm multi-agent workflow named `{name}`.

## Steps

1. Add dependencies to `Cargo.toml`:
```toml
vanswarm-core = {{ path = "crates/core" }}
tokio = {{ version = "1", features = ["full"] }}
```

2. Create the workflow:
```rust
use std::sync::Arc;

use vanswarm_core::{{
    config::{{AgentConfig, ModelConfig}},
    providers::AnthropicProvider,
    react::{{ReActAgent, run_agent}},
    LocalToolRegistry, TimeTool,
}};

/// A two-step workflow: first agent drafts, second agent reviews.
async fn {name}(input: &str) -> anyhow::Result<String> {{
    let provider = Arc::new(AnthropicProvider::from_env()?);
    let tools = Arc::new(LocalToolRegistry::new().register(TimeTool));

    // Step 1: draft.
    let drafter = ReActAgent::new(
        AgentConfig::new("drafter", ModelConfig::new("claude-opus-4-6"))
            .with_system_prompt("Draft a response to the user's request."),
        Arc::clone(&provider),
        Arc::clone(&tools),
    );
    let draft = run_agent(&drafter, input).await?;

    // Step 2: review / refine.
    let reviewer = ReActAgent::new(
        AgentConfig::new("reviewer", ModelConfig::new("claude-opus-4-6"))
            .with_system_prompt(
                "Review and improve the draft below. Return only the improved text.",
            )
            .with_max_iterations(5),
        Arc::clone(&provider),
        Arc::clone(&tools),
    );
    let refined = run_agent(&reviewer, &format!("Draft:\n{{draft}}")).await?;

    Ok(refined)
}}

#[tokio::main]
async fn main() -> anyhow::Result<()> {{
    let result = {name}("Explain Rust ownership in one paragraph.").await?;
    println!("{{}}", result);
    Ok(())
}}
```

## Next steps
- Add error handling and retries between steps.
- Use `EvaluatorOptimizer` pattern for iterative refinement loops.
- Use `PlanAndExecute` or `Supervisor` for more complex orchestration.
- Persist state with the three-tier memory system (episodic → semantic → graph).
"#
    )
}

fn tool_scaffold_prompt(tool_name: &str) -> String {
    let pascal = to_pascal_case(tool_name);
    format!(
        r#"Add a custom tool named `{tool_name}` to a VanSwarm agent.

## Steps

1. Implement the `Tool` trait:
```rust
use vanswarm_core::traits::tool::{{Tool, ToolResult}};
use schemars::JsonSchema;
use serde::Deserialize;

/// Input schema for `{tool_name}`.
#[derive(Debug, Deserialize, JsonSchema)]
pub struct {pascal}Input {{
    /// Describe the input field here.
    pub query: String,
}}

/// The tool implementation.
pub struct {pascal};

#[async_trait::async_trait]
impl Tool for {pascal} {{
    fn name(&self) -> &str {{
        "{tool_name}"
    }}

    fn description(&self) -> &str {{
        "Describe what {tool_name} does."
    }}

    fn input_schema(&self) -> serde_json::Value {{
        let schema = schemars::schema_for!({pascal}Input);
        serde_json::to_value(schema).expect("schema serialization failed")
    }}

    async fn call(&self, input: serde_json::Value) -> ToolResult {{
        let args: {pascal}Input = serde_json::from_value(input)
            .map_err(|e| format!("invalid input: {{e}}"))?;
        // TODO: implement your logic here.
        Ok(format!("Result for: {{}}", args.query))
    }}
}}
```

2. Register the tool with your agent:
```rust
let tools = Arc::new(
    LocalToolRegistry::new()
        .register(TimeTool)      // built-in
        .register({pascal})      // your new tool
);
let agent = ReActAgent::new(config, provider, tools);
```

## Notes
- `ToolResult` is `Result<String, String>`.
- Tool names must be unique within a registry (snake_case recommended).
- The input schema drives what arguments the LLM can pass; keep it minimal.
"#
    )
}

/// Convert `snake_case` or `kebab-case` to `PascalCase`.
fn to_pascal_case(s: &str) -> String {
    s.split(|c: char| c == '_' || c == '-')
        .map(|w| {
            let mut chars = w.chars();
            match chars.next() {
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

// ─────────────────────────────────────────────────────────────────────────────
// ServerHandler impl (generated body via #[tool_handler])
// ─────────────────────────────────────────────────────────────────────────────

#[tool_handler]
impl ServerHandler for FrameworkTools {
    fn get_info(&self) -> ServerInfo {
        let provider_note = if self.provider.is_some() {
            format!(
                "LLM ready ({}, model: {}). ",
                self.provider_name, self.default_model
            )
        } else {
            "LLM NOT configured — set ANTHROPIC_API_KEY, OPENAI_API_KEY, or GEMINI_API_KEY. \
             Memory tools work without a provider. "
                .to_string()
        };

        let docs_note = match &self.docs_root {
            Some(_) => "Docs available via resources/list. ".to_string(),
            None => "Docs not configured (set VANSWARM_DOCS_ROOT). ".to_string(),
        };

        ServerInfo {
            protocol_version: ProtocolVersion::LATEST,
            capabilities: ServerCapabilities::builder()
                .enable_tools()
                .enable_resources()
                .enable_prompts()
                .build(),
            server_info: Implementation {
                name: "vanswarm-mcp-server".into(),
                version: env!("CARGO_PKG_VERSION").into(),
                ..Default::default()
            },
            instructions: Some(
                format!(
                    "VanSwarm Agent Framework MCP server. \
                     {provider_note}\
                     {docs_note}\
                     Tools — vanswarm_run_agent: Run a full ReAct reasoning loop \
                       (returns answer + metrics). \
                     vanswarm_memory_store/search/recent: Episodic memory. \
                     vanswarm_framework_info: Version and status. \
                     Resources — vanswarm://docs/* for VanSwarm documentation \
                       (use resources/list then resources/read). \
                     Prompts — new_agent_scaffold, new_workflow_scaffold, add_tool_scaffold \
                       (use prompts/get with required arguments).",
                    provider_note = provider_note,
                    docs_note = docs_note,
                )
                .into(),
            ),
        }
    }

    // ──────────────────────────────────────────────────────────────────────
    // Resources: vanswarm://docs/* → documentation directory
    // ──────────────────────────────────────────────────────────────────────

    async fn list_resources(
        &self,
        _request: Option<PaginatedRequestParams>,
        _context: RequestContext<RoleServer>,
    ) -> Result<ListResourcesResult, McpError> {
        let resources = match &self.docs_root {
            Some(root) => collect_doc_resources(root),
            None => Vec::new(),
        };
        tracing::debug!(count = resources.len(), "resources/list");
        Ok(ListResourcesResult::with_all_items(resources))
    }

    async fn read_resource(
        &self,
        request: ReadResourceRequestParams,
        _context: RequestContext<RoleServer>,
    ) -> Result<ReadResourceResult, McpError> {
        let docs_root = self.docs_root.as_deref().ok_or_else(|| {
            McpError::invalid_params(
                "Docs root not configured. Set VANSWARM_DOCS_ROOT to enable resources.",
                None,
            )
        })?;

        let path = resolve_doc_uri(docs_root, &request.uri).ok_or_else(|| {
            McpError::invalid_params(
                format!(
                    "Invalid or unsafe resource URI '{}'. \
                     Only vanswarm://docs/* URIs within the configured docs root are allowed.",
                    request.uri
                ),
                None,
            )
        })?;

        let text = std::fs::read_to_string(&path).map_err(|e| {
            McpError::invalid_params(
                format!("Cannot read resource '{}': {}", request.uri, e),
                None,
            )
        })?;

        tracing::debug!(uri = %request.uri, "resources/read");
        Ok(ReadResourceResult {
            contents: vec![ResourceContents::text(text, &request.uri)],
        })
    }

    // ──────────────────────────────────────────────────────────────────────
    // Prompts: scaffold templates for agents, workflows, and tools
    // ──────────────────────────────────────────────────────────────────────

    async fn list_prompts(
        &self,
        _request: Option<PaginatedRequestParams>,
        _context: RequestContext<RoleServer>,
    ) -> Result<ListPromptsResult, McpError> {
        let prompts = vec![
            Prompt::new(
                "new_agent_scaffold",
                Some("Generate boilerplate Rust code for a new VanSwarm ReAct agent."),
                Some(vec![
                    PromptArgument {
                        name: "name".to_string(),
                        title: None,
                        description: Some(
                            "Snake-case name for the agent (e.g. \"my_agent\").".to_string(),
                        ),
                        required: Some(true),
                    },
                    PromptArgument {
                        name: "model".to_string(),
                        title: None,
                        description: Some(
                            "LLM model to use (e.g. \"claude-opus-4-6\", \"gpt-4o\"). \
                             Defaults to \"claude-opus-4-6\" if omitted."
                                .to_string(),
                        ),
                        required: Some(false),
                    },
                ]),
            ),
            Prompt::new(
                "new_workflow_scaffold",
                Some(
                    "Generate boilerplate Rust code for a new VanSwarm multi-agent workflow.",
                ),
                Some(vec![PromptArgument {
                    name: "name".to_string(),
                    title: None,
                    description: Some(
                        "Snake-case name for the workflow function (e.g. \"draft_review\")."
                            .to_string(),
                    ),
                    required: Some(true),
                }]),
            ),
            Prompt::new(
                "add_tool_scaffold",
                Some(
                    "Generate boilerplate Rust code for a new VanSwarm tool \
                     that can be registered with any ReAct agent.",
                ),
                Some(vec![PromptArgument {
                    name: "tool_name".to_string(),
                    title: None,
                    description: Some(
                        "Snake-case tool name (e.g. \"web_search\", \"read_file\").".to_string(),
                    ),
                    required: Some(true),
                }]),
            ),
        ];
        Ok(ListPromptsResult::with_all_items(prompts))
    }

    async fn get_prompt(
        &self,
        request: GetPromptRequestParams,
        _context: RequestContext<RoleServer>,
    ) -> Result<GetPromptResult, McpError> {
        let args = request.arguments.unwrap_or_default();
        let get = |key: &str| {
            args.get(key).and_then(|v| v.as_str()).unwrap_or("").to_string()
        };

        match request.name.as_str() {
            "new_agent_scaffold" => {
                let name = get("name");
                if name.is_empty() {
                    return Err(McpError::invalid_params(
                        "'name' argument is required for new_agent_scaffold.",
                        None,
                    ));
                }
                let model = get("model");
                let model = if model.is_empty() { "claude-opus-4-6".to_string() } else { model };
                let text = agent_scaffold_prompt(&name, &model);
                Ok(GetPromptResult {
                    description: Some(format!(
                        "VanSwarm ReAct agent scaffold for '{name}' using '{model}'"
                    )),
                    messages: vec![PromptMessage::new_text(PromptMessageRole::User, text)],
                })
            }

            "new_workflow_scaffold" => {
                let name = get("name");
                if name.is_empty() {
                    return Err(McpError::invalid_params(
                        "'name' argument is required for new_workflow_scaffold.",
                        None,
                    ));
                }
                let text = workflow_scaffold_prompt(&name);
                Ok(GetPromptResult {
                    description: Some(format!("VanSwarm workflow scaffold for '{name}'")),
                    messages: vec![PromptMessage::new_text(PromptMessageRole::User, text)],
                })
            }

            "add_tool_scaffold" => {
                let tool_name = get("tool_name");
                if tool_name.is_empty() {
                    return Err(McpError::invalid_params(
                        "'tool_name' argument is required for add_tool_scaffold.",
                        None,
                    ));
                }
                let text = tool_scaffold_prompt(&tool_name);
                Ok(GetPromptResult {
                    description: Some(format!("VanSwarm tool scaffold for '{tool_name}'")),
                    messages: vec![PromptMessage::new_text(PromptMessageRole::User, text)],
                })
            }

            other => Err(McpError::invalid_params(
                format!(
                    "Unknown prompt '{other}'. Available prompts: \
                     new_agent_scaffold, new_workflow_scaffold, add_tool_scaffold."
                ),
                None,
            )),
        }
    }
}
