//! VanSwarm MCP server — tool handlers.
//!
//! Exposes the VanSwarm agent framework as MCP tools so any MCP-capable
//! client (Cursor, Claude Desktop, etc.) can:
//!
//! * Run a full ReAct reasoning loop via `vanswarm_run_agent`.
//! * Store and search episodic memory via `vanswarm_memory_*` tools.
//! * Inspect framework status via `vanswarm_framework_info`.
//!
//! The server auto-detects the LLM provider at startup by checking:
//!   `ANTHROPIC_API_KEY` → AnthropicProvider (default model: claude-opus-4-6)
//!   `OPENAI_API_KEY`    → OpenAiProvider    (default model: gpt-4o)
//!   `GEMINI_API_KEY`    → GeminiProvider    (default model: gemini-2.0-flash)
//!
//! Override the model with `RUSTMASTRA_MODEL`.

use std::sync::Arc;

use rmcp::{
    handler::server::{router::tool::ToolRouter, wrapper::Parameters},
    model::{
        CallToolResult, Content, ErrorData as McpError, Implementation, ProtocolVersion,
        ServerCapabilities, ServerInfo,
    },
    tool, tool_handler, tool_router, ServerHandler,
};
use schemars::JsonSchema;
use serde::Deserialize;

use vanswarm_core::{
    config::{AgentConfig, ModelConfig},
    providers::ModelProvider,
    react::{run_agent, ReActAgent},
    LocalToolRegistry, TimeTool,
};
use vanswarm_memory::{EpisodicMemory, Memory, MemoryEntry};

// ─────────────────────────────────────────────────────────────────────────────
// Parameter structs (schemars 1.0 JsonSchema required by rmcp #[tool] macro)
// ─────────────────────────────────────────────────────────────────────────────

/// Parameters for `vanswarm_run_agent`.
#[derive(Debug, Deserialize, JsonSchema)]
pub struct RunAgentParams {
    /// The user prompt or task description for the agent to solve.
    pub prompt: String,

    /// Optional system prompt to set the agent's persona or constraints.
    /// Example: "You are a concise Rust expert. Use tools where appropriate."
    #[serde(default)]
    pub system_prompt: Option<String>,

    /// LLM model override. Defaults to the server-detected default.
    /// Examples: "claude-opus-4-6", "gpt-4o", "gemini-2.0-flash"
    #[serde(default)]
    pub model: Option<String>,

    /// Maximum number of ReAct iterations before the agent gives up.
    /// Default: 10. Lower for faster responses; raise for complex multi-step tasks.
    #[serde(default)]
    pub max_iterations: Option<u32>,
}

/// Parameters for `vanswarm_memory_store`.
#[derive(Debug, Deserialize, JsonSchema)]
pub struct MemoryStoreParams {
    /// The fact, observation, or event to remember.
    pub content: String,
}

/// Parameters for `vanswarm_memory_search`.
#[derive(Debug, Deserialize, JsonSchema)]
pub struct MemorySearchParams {
    /// Full-text search query (case-insensitive substring match).
    pub query: String,

    /// Maximum number of results to return. Default: 10.
    #[serde(default)]
    pub limit: Option<u32>,
}

/// Parameters for `vanswarm_memory_recent`.
#[derive(Debug, Deserialize, JsonSchema)]
pub struct MemoryRecentParams {
    /// Maximum number of entries to return, newest first. Default: 10.
    #[serde(default)]
    pub limit: Option<u32>,
}

/// Empty parameter struct for `vanswarm_framework_info`.
#[derive(Debug, Deserialize, JsonSchema)]
pub struct NoParams {}

// ─────────────────────────────────────────────────────────────────────────────
// FrameworkTools — shared state + tool router
// ─────────────────────────────────────────────────────────────────────────────

/// Composite MCP server exposing VanSwarm agent framework capabilities.
///
/// All fields are `Clone` + `Send + Sync` so the struct can be shared across
/// concurrent MCP requests via `Arc`-wrapped state.
#[derive(Clone)]
pub struct FrameworkTools {
    /// Auto-detected LLM provider. `None` if no API key was found at startup.
    provider: Option<Arc<dyn ModelProvider>>,
    /// Default model for the detected provider (e.g. "claude-opus-4-6").
    default_model: String,
    /// Name of the active provider for display in `framework_info`.
    provider_name: String,
    /// In-process episodic memory — FIFO, 1 000 entries.
    memory: Arc<EpisodicMemory>,
    /// Routing table generated by `#[tool_router]`.
    tool_router: ToolRouter<Self>,
}

#[tool_router]
impl FrameworkTools {
    pub fn new(
        provider: Option<Arc<dyn ModelProvider>>,
        default_model: impl Into<String>,
        provider_name: impl Into<String>,
    ) -> Self {
        Self {
            provider,
            default_model: default_model.into(),
            provider_name: provider_name.into(),
            memory: Arc::new(EpisodicMemory::new(1_000)),
            tool_router: Self::tool_router(),
        }
    }

    // ──────────────────────────────────────────────────────────────────────
    // Agent tool
    // ──────────────────────────────────────────────────────────────────────

    /// Run a VanSwarm ReAct agent on the given prompt.
    ///
    /// The agent reasons step-by-step (Thought → Action → Observation) and may
    /// call built-in tools (`time`) until it produces a final answer or hits
    /// `max_iterations`. Returns the final answer as plain text.
    #[tool(description = "Run a VanSwarm ReAct agent. The agent reasons step-by-step, calling tools as needed, until it produces a final answer. Built-in tool: `time` (current UTC time). Ideal for multi-step reasoning, research, planning, and Q&A. Returns the final answer as plain text.")]
    pub async fn vanswarm_run_agent(
        &self,
        Parameters(params): Parameters<RunAgentParams>,
    ) -> Result<CallToolResult, McpError> {
        let provider = match &self.provider {
            Some(p) => Arc::clone(p),
            None => {
                return Err(McpError::invalid_params(
                    "No LLM provider configured. Set ANTHROPIC_API_KEY, OPENAI_API_KEY, \
                     or GEMINI_API_KEY before calling run_agent.",
                    None,
                ))
            }
        };

        let model = params.model
            .as_deref()
            .unwrap_or(&self.default_model)
            .to_string();
        let max_iter = params.max_iterations.unwrap_or(10) as usize;

        let mut config =
            AgentConfig::new("mcp-agent", ModelConfig::new(model)).with_max_iterations(max_iter);

        if let Some(sys) = params.system_prompt {
            config = config.with_system_prompt(sys);
        }

        // Include built-in tools available to the agent during the ReAct loop.
        let registry = Arc::new(LocalToolRegistry::new().register(TimeTool));

        let agent = ReActAgent::new(config, provider, registry);

        match run_agent(&agent, params.prompt).await {
            Ok(answer) => Ok(CallToolResult::success(vec![Content::text(answer)])),
            Err(e) => Err(McpError {
                code: rmcp::model::ErrorCode::INTERNAL_ERROR,
                message: e.to_string().into(),
                data: None,
            }),
        }
    }

    // ──────────────────────────────────────────────────────────────────────
    // Memory tools
    // ──────────────────────────────────────────────────────────────────────

    /// Store a fact or observation in the agent's episodic memory.
    ///
    /// Memory persists for the lifetime of the server process (FIFO, 1 000-entry
    /// cap). Use to share context between multiple `run_agent` calls.
    /// Returns the UUID of the stored entry.
    #[tool(description = "Store a fact, observation, or event in the agent's episodic memory. Memory persists for the server's lifetime (FIFO, 1 000-entry cap). Use to share context across run_agent calls. Returns the stored entry's UUID.")]
    pub async fn vanswarm_memory_store(
        &self,
        Parameters(params): Parameters<MemoryStoreParams>,
    ) -> Result<CallToolResult, McpError> {
        let entry = MemoryEntry::new(params.content);
        let id = entry.id;
        self.memory.store(entry).await.map_err(|e| McpError {
            code: rmcp::model::ErrorCode::INTERNAL_ERROR,
            message: e.to_string().into(),
            data: None,
        })?;
        Ok(CallToolResult::success(vec![Content::text(format!("stored id={id}"))]))
    }

    /// Full-text search in the agent's episodic memory.
    ///
    /// Performs a case-insensitive substring match against all stored entries.
    /// Returns matching entries formatted as `[id] timestamp — content`.
    #[tool(description = "Full-text search in episodic memory. Case-insensitive substring match. Returns matching entries as `[id] timestamp — content` lines, newest first.")]
    pub async fn vanswarm_memory_search(
        &self,
        Parameters(params): Parameters<MemorySearchParams>,
    ) -> Result<CallToolResult, McpError> {
        let limit = params.limit.unwrap_or(10) as usize;
        let entries = self.memory.search(&params.query, limit).await.map_err(|e| McpError {
            code: rmcp::model::ErrorCode::INTERNAL_ERROR,
            message: e.to_string().into(),
            data: None,
        })?;

        if entries.is_empty() {
            return Ok(CallToolResult::success(vec![Content::text(
                "No matching entries found.",
            )]));
        }

        let lines: Vec<String> = entries
            .iter()
            .map(|e| {
                format!(
                    "[{}] {} — {}",
                    e.id,
                    e.created_at.format("%Y-%m-%dT%H:%M:%SZ"),
                    e.content
                )
            })
            .collect();
        Ok(CallToolResult::success(vec![Content::text(lines.join("\n"))]))
    }

    /// Return the most recent entries in the agent's episodic memory.
    ///
    /// Entries are returned newest first, formatted as `[id] timestamp — content`.
    #[tool(description = "Return the most recent entries in episodic memory, newest first. Formatted as `[id] timestamp — content` lines.")]
    pub async fn vanswarm_memory_recent(
        &self,
        Parameters(params): Parameters<MemoryRecentParams>,
    ) -> Result<CallToolResult, McpError> {
        let limit = params.limit.unwrap_or(10) as usize;
        let entries = self.memory.recent(limit).await.map_err(|e| McpError {
            code: rmcp::model::ErrorCode::INTERNAL_ERROR,
            message: e.to_string().into(),
            data: None,
        })?;

        if entries.is_empty() {
            return Ok(CallToolResult::success(vec![Content::text("Memory is empty.")]));
        }

        let lines: Vec<String> = entries
            .iter()
            .map(|e| {
                format!(
                    "[{}] {} — {}",
                    e.id,
                    e.created_at.format("%Y-%m-%dT%H:%M:%SZ"),
                    e.content
                )
            })
            .collect();
        Ok(CallToolResult::success(vec![Content::text(lines.join("\n"))]))
    }

    // ──────────────────────────────────────────────────────────────────────
    // Info
    // ──────────────────────────────────────────────────────────────────────

    /// Return VanSwarm framework version, provider status, and capabilities.
    #[tool(description = "Return framework version, configured LLM provider, default model, and available capabilities. Use to check server health and configuration.")]
    pub async fn vanswarm_framework_info(
        &self,
        _params: Parameters<NoParams>,
    ) -> Result<CallToolResult, McpError> {
        let provider_status = if self.provider.is_some() {
            format!(
                "connected (provider: {}, default model: {})",
                self.provider_name, self.default_model
            )
        } else {
            "NOT configured — set ANTHROPIC_API_KEY, OPENAI_API_KEY, or GEMINI_API_KEY".to_string()
        };

        let info = format!(
            "VanSwarm Agent Framework\n\
             Version:        {version}\n\
             LLM provider:   {provider_status}\n\
             Built-in tools: time (UTC clock)\n\
             Memory:         episodic in-process (FIFO, 1 000 entries)\n\
             Agent pattern:  ReAct (Thought → Action → Observation)\n\
             Other patterns: EvaluatorOptimizer, PlanAndExecute, Supervisor\n\
             Providers:      Anthropic, OpenAI, Gemini\n\
             Telemetry:      run traces, token usage, cost estimation",
            version = env!("CARGO_PKG_VERSION"),
            provider_status = provider_status,
        );
        Ok(CallToolResult::success(vec![Content::text(info)]))
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// ServerHandler impl (generated body via #[tool_handler])
// ─────────────────────────────────────────────────────────────────────────────

#[tool_handler]
impl ServerHandler for FrameworkTools {
    fn get_info(&self) -> ServerInfo {
        let provider_note = if self.provider.is_some() {
            format!(
                "LLM ready ({}, model: {}). ",
                self.provider_name, self.default_model
            )
        } else {
            "LLM NOT configured — set ANTHROPIC_API_KEY, OPENAI_API_KEY, or GEMINI_API_KEY. \
             Memory tools work without a provider. "
                .to_string()
        };

        ServerInfo {
            protocol_version: ProtocolVersion::LATEST,
            capabilities: ServerCapabilities::builder().enable_tools().build(),
            server_info: Implementation {
                name: "vanswarm-mcp-server".into(),
                version: env!("CARGO_PKG_VERSION").into(),
                ..Default::default()
            },
            instructions: Some(
                format!(
                    "VanSwarm Agent Framework MCP server. \
                     {provider_note}\
                     Tools — \
                     vanswarm_run_agent: Run a full ReAct reasoning loop (multi-step, \
                       tool-calling, reflection). Parameters: prompt (required), \
                       system_prompt, model, max_iterations. \
                     vanswarm_memory_store: Store a fact in ephemeral episodic memory \
                       (persists for server lifetime, 1 000-entry FIFO). \
                     vanswarm_memory_search: Full-text keyword search in episodic memory. \
                     vanswarm_memory_recent: List the most recent memory entries. \
                     vanswarm_framework_info: Framework version and provider status. \
                     Note: run_agent dispatches concurrently — multiple calls are safe.",
                    provider_note = provider_note,
                )
                .into(),
            ),
        }
    }
}
